name: npm-publish
on:
  release:
    types: [created]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test
  publish:
    runs-on: ubuntu-last
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        if: "!contains(github.event.release.name, 'beta')"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish as beta
        if: contains(github.event.release.name, 'beta')
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
